manifest:
  defaults:
    revision: main

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
      
    - name: nxp-pro-support
      url-base: https://github.com/nxp-pro-support

  defaults:
    remote: zephyrproject-rtos
    revision: main

  projects:

    - name: zephyr
      remote: zephyrproject-rtos
      repo-path: zephyr
      revision: main
      import:
        name-allowlist:
          - mbedtls
          - zcbor
          - hal_nxp
          - cmsis
          - cmsis_6
          - open-amp
    
    - name: zephyr-module-sample
      remote: nxp-pro-support
      repo-path: zephyr-module-sample
      revision: main
      path: ./modules/module-sample

  self:
    path: zephyr_debug
